### ISSUE TITLE
A bunch of approved entries are on the list with (???) in place of their name

### ISSUE THREAD

**Issue by jaerockets** [Hiyori-API/checker_mal#17]
It's clogging it up quite a bit

**Comment by jaerockets** [comment]
names have been corrected, but still a bunch of approved anime on the list

**Comment by purarue** [comment]
Hi, yeah...

seems that something changed with MAL, seems to have to with the ordering on the search pages, or it not listing the IDs in order anymore, which messed up a bunch of the logic for how this adds/removes approved IDs

currently it looks to have added unapproved entry to the approved set as well (I think?), it should still continue to list new unapproved entries I believe, it'll just also list approved ones

I likely won't have time to fix it this week, but will update here when I'm able to

**Comment by purarue** [comment]
@jaerockets pushed something that seems to have fixed it, if you see any issues let me know

**Comment by jaerockets** [comment]
yeah I noticed it was working again earlier today, convenient timing bc I'm using the data for a little live feed program I'm making for myself that I wanted to work on today :)
